name: Simple Update
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update timestamp
        run: |
          git config user.name "gansgajder-web"
          git config user.email "gansgajder-web@users.noreply.github.com"
          echo "Оновлено: $(date +'%d.%m.%Y о %H:%M')" > update-log.txt
          git add update-log.txt
          git commit -m "Автоматичне оновлення часу"
          git push
