name: Auto Update Hub
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  update-hub:
    runs-on: ubuntu-latest
    permissions: contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Update Status File
        run: |
          git config user.name "gansgajder-web"
          git config user.email "gansgajder-web@users.noreply.github.com"
          echo "Останнє оновлення: $(date +'%d.%m.%Y %H:%M')" > status.txt
          git add status.txt
          git commit -m "Оновлення статусу"
          git push
