name: Auto Update Para

on:
  workflow_dispatch: # Можна запускати вручну кнопкою на сайті
  schedule:
    - cron: '0 12 * * *' # Запускається щодня о 12:00 дня

jobs:
  update-repo:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add timestamp to log
        run: |
          echo "Останнє оновлення хмарою: $(date)" >> update-log.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Автоматичне оновлення з хмари 🤖"
          file_pattern: 'update-log.txt'
